# api/config/packages/api_platform.yaml
api_platform:
    title: 'API newsletter'
    description: 'Newsapp - Api de newsletter'
    version: '1.0.0'
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header